### ISSUE TITLE
The gradle dependency is not working in android studio

### ISSUE THREAD

**Issue by parthvora25** [Cutta/TagView#16]
I did everything possible but its showing the message.

> Failed to resolve: com.github.Cutta:TagView:c15dd8288a
> <a href="openFile:/home/espl/AndroidStudioProjects/WON/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by Cutta** [comment]
I try it and It works. May be you put "jitpack" line wrong place.
You should put it in "repositories" block which is not in buildscript block. 

repositories {
    maven {
        url "https://jitpack.io"
    }
}
android {...}

**Comment by parthvora25** [comment]
Thanks!!!
