### ISSUE TITLE
Need a removeAllTags method ?

### ISSUE THREAD

**Issue by w3hacker** [Cutta/TagView#2]
I want to remove all views of tagview, but mTags doesn't clear.So I add a removeAllTags method.

**Comment by w3hacker** [comment]
```
public void removeAllTags() {
     mTags.clear();
 }
```

**Comment by Cutta** [comment]
@w3hacker  I added <a href = "https://github.com/Cutta/TagView/blob/master/app/src/main/java/cuneyt/example/com/tagview/Tag/TagView.java">removeAll()</a> method. You can use it for remove all tags from parent layout.
