### ISSUE TITLE
background color

### ISSUE THREAD

**Issue by ssahilsahil798** [Cutta/TagView#22]
how to change background colors in your library?

**Comment by Cutta** [comment]
You can change background color of each Tag like this:
  `   tag.layoutColor = Color.parseColor("#FFFF00");`
after that  the library changes the color with these lines:
```
..
  GradientDrawable gdNormal = new GradientDrawable();
        gdNormal.setColor(tag.layoutColor);
..
```
You can see from [here] .(https://github.com/Cutta/TagView/blob/master/library/src/main/java/com/cunoraz/tagview/TagView.java)

**Comment by iganovir** [comment]
i still dont understand how to use this feature. I added tags by String array . I've called the method too but it returns tag on null object. Any ideas how to use this feature? Thank you.
