### ISSUE TITLE
TagView.removeAll and remove(i) dosn't work

### ISSUE THREAD

**Issue by lwj1994** [Cutta/TagView#23]
I have a bug.

first. i add 4 Tag in A Fragment. and then i start to B Fragment  to update Tag . A fragment also need to update sync.  and i Transfer a List<Tag>  to A fragment with EventBus.
 in A Fragment , once i get Event , i call  TagView.removeall(),then add new Tag. but the 4  previous Tag is still visible.
but my Log tell me, after removeAll , the TagView.getChildCount() is 0. so it should be removeall.

 tagView.removeAll();
 Logger.e(TAG,"tagView.getChildCount() = "+tagView.getChildCount());
Can you help me ?

**Comment by lwj1994** [comment]
I have a bug.  
first. i add 4 Tag.  and then i removeAll to update . but the 4 Tag is still visible.
but my Log tell me, after removeAll , the TagView.getChildCount() is 0.  so it should be removeall.  

     tagView.removeAll();
     Logger.e(TAG,"tagView.getChildCount() = "+tagView.getChildCount());
    
Can you help me ?

**Comment by lwj1994** [comment]
i solved it.
when update new Tag  
i use TagView.add(List<Tag> list)  instead of TagView.add(Tag) one by one in a for loop.  

i don't know why so

**Comment by Cutta** [comment]
I fixed it. thanks for issue. It was a good point.

**Comment by lwj1994** [comment]
thank you very much. your library help me much
