### ISSUE TITLE
How do I delete tags using 'X' button?

### ISSUE THREAD

**Issue by syedsouban** [Cutta/TagView#43]
I am using a tagview and adding tags dynamically. But I can't find the 'x' aka delete button on the tag.

**Comment by Cutta** [comment]
Hi @syedsouban  you should set the tag.isDeletable variable. Check this line:
https://github.com/Cutta/TagView/blob/a8a348804341913e6b07d73027d5db5e246203f7/app/src/main/java/cuneyt/example/com/tagview/Activity/MainActivity.java#L141

**Comment by syedsouban** [comment]
Hi @Cutta, thanks for the answering :) It worked.

**Comment by Cutta** [comment]
You are welcome :)
