### ISSUE TITLE
Methods count & gradle build settings

### ISSUE THREAD

**Issue by meierjan** [Cutta/TagView#8]
I would love to see the gradle settings to include this into your app in the README.md as well as the methods count as this plays a huge role in modern android development.

If you want me to I can create a pull-request.

Here are the Infos:
#### Gradle
```
repositories {
    maven {
        url "https://jitpack.io"
    }
}
```
```
dependencies {
    compile 'com.github.Cutta:TagView:c15dd8288a'
}
```
Taken from [Android-Arsenal](https://android-arsenal.com/details/1/2566)

#### Methods-Count
The badge indicating the methods-count.
<a href="http://www.methodscount.com/?lib=com.github.Cutta%3ATagView%3Ac15dd8288a"><img src="https://img.shields.io/badge/Methods and size-core: 104 | deps: 15068 | 27 KB-e91e63.svg"></img></a>
Taken from [methodscount.com](http://www.methodscount.com/?lib=com.github.Cutta%3ATagView%3Ac15dd8288a)

**Comment by Cutta** [comment]
I added the infos. Thank you @meierjan
